Hw5
DennKK/link-tracker pull request #6
Opened 2024-03-17 20:07 UTC by DennKK

2024-03-21 09:06 UTC, DennKK commented
В эту ветку случайно попали коммиты из ветки hw5-bonus

2024-03-24 10:34 UTC, YuriiKondratov requested changes

2024-03-24 10:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcChatService.java
> +        ChatDto chat = new ChatDto(tgChatId, null);
А почему registeredAt = null?

2024-03-24 10:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/domain/repository/jdbc/JdbcLinkRepository.java
> +    public void map(LinkDto link, ChatDto chat) {
Давай тут просто айдишники передадим, зачем нам полностью LinkDto и ChatDto?

2024-03-24 10:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/domain/repository/jdbc/JdbcLinkRepository.java
> +    public void unmap(LinkDto link, ChatDto chat) {
И тут тоже айдишников достаточно

2024-03-24 10:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkUpdater.java
> +        Collection<LinkDto> oldLinks = jdbcLinkService.getOldLinks(updateFrequency);
А зачем ты его жеско с jdbcLinkService связал? Придется точно такой же класс писать для jooqLinkService. Тебе же тут без разницы каким образом достаются ссылки - через jdbc или через jooq. Давай вынесем getOldLinks в интерфейс и поменяем тут на зависимость от интерфейса.

2024-03-24 10:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/client/tgbot/BotClient.java
> +            jdbcLinkService.getChatsForLink(link).stream().map(ChatDto::getChatId).toList();
Тут вообще не должно быть обращения к базе и уж тем более жесткой завязки на JDBC. Вынеси это в LinkUpdater и убери зависимость от JDBC, везде должна быть зависимость от интерфейса, чтобы ты мог легко поменять JDBC на JOOQ

2024-03-24 13:01 UTC, DennKK commented on scrapper/src/main/java/edu/java/scrapper/service/jdbc/JdbcLinkUpdater.java
> +        Collection<LinkDto> oldLinks = jdbcLinkService.getOldLinks(updateFrequency);
В пятом бонусном дз, когда добавлял jooq, понял, что так лучше не делать, поэтому изменения связанные с LinkUpdater в ветке hw5 bonus

2024-03-24 14:35 UTC, DennKK commented
Когда подключал jooq осознал некоторые фундаментальные проблемы, по этой причине логика в бонусном дз сильно отличается и теперь в эту ветку неудобно вносить изменения. Исправления ошибок внесу в ветку hw5 bonus

2024-03-24 14:38 UTC, YuriiKondratov commented
Постарайся чтобы в будущем не было таких ситуаций. Из-за этого дико неудобно проверять.

2024-05-17 18:41 UTC, merged