Hw6
DennKK/link-tracker pull request #8
Opened 2024-03-24 20:06 UTC by DennKK

2024-03-27 15:39 UTC, YuriiKondratov commented
Проверять домашку буду немного позже, но сразу говорю, что в этом PR должны быть ТОЛЬКО изменения, относящиеся к ДЗ 6. А я вижу здесь и миграции и jOOQ. В общем поправь пожалуйста, иначе проверить это у меня не получится;

2024-03-27 15:40 UTC, YuriiKondratov requested changes
Указал выше что нужно поправить

2024-03-27 18:37 UTC, DennKK commented
Комментарии увидел, фикшу

2024-03-29 11:11 UTC, DennKK commented
Добавил больше логирования ([c913856](https://github.com/DennKK/link-tracker/pull/8/commits/c91385644853006b1f65e2d9ef1ee2e0946b72a3)), но кажется метод update вообще не запускается по расписанию. Пока не удается понять в чем дело. Комментарий про то, что взаимодействие LinkUpdaterScheduler с клиентами нужно вынести в отдельный модуль, помню. Чуть позже добавлю

2024-03-29 17:03 UTC, DennKK commented
По какой-то причине метод update в LinkUpdaterScheduler не запускаетcя по расписанию. Пока не могу выяснить в чем проблема

2024-03-30 09:31 UTC, YuriiKondratov approved these changes

2024-03-30 09:31 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/scrapper/configuration/domain_config/JdbcAccessConfiguration.java
> +package edu.java.scrapper.configuration.domain_config;
в названиях пакетов нижнее подчеркивание не используется

2024-05-17 18:50 UTC, merged